Issue undef1
ChicoState/PantryNode pull request #103
Opened 2023-04-06 17:51 UTC by Anoushka444

Removed the errors and added the ignore file.

2023-04-07 05:03 UTC, jayrevolinskyjr requested changes
My only concern is that there are a massive amount of changes to the package-lock.json, I thought it was a part of the .gitignore? Besides that and the merge issues, it looks good.

2023-04-08 06:50 UTC, jayrevolinskyjr commented
Looks like the merge conflicts and package-lock.json problem is related to Issue [104](https://github.com/ChicoState/PantryNode/issues/104)

2023-04-10 22:41 UTC, AbhinavReddy-Dev commented
To resolve the `package-lock.json` errors, the process is to reinstall the packages after resolving the conflicts in `package.json`. This will update the `package-lock.json` file and the conflicts are auto resolved by `npm`.

2023-04-11 05:16 UTC, Jooms commented
Don't forget to rebase :)

2023-04-11 05:16 UTC, Jooms requested changes
Rebase so we can see the CI run

2023-04-11 05:16 UTC, Jooms commented on console.log(err))
Remove this file

2023-04-11 05:16 UTC, Jooms commented on git
Remove this file

2023-04-11 05:16 UTC, Jooms commented on {
Remove this file.

2023-04-11 05:16 UTC, Jooms commented on routes/users.js
nit: (meaning optional)
You didn't change anything in this file. So remove the extra line you added.

Or the cool git way
```shell
git reset main -- backend/routes/users.js
```

2023-04-12 07:40 UTC, Anoushka444 commented on {
Done

2023-04-12 07:40 UTC, Anoushka444 commented on console.log(err))
Done

2023-04-12 07:43 UTC, Anoushka444 reviewed
Reviews addressed!

2023-04-12 07:44 UTC, Anoushka444 commented on routes/users.js
Done

2023-04-12 18:21 UTC, jayrevolinskyjr approved these changes

2023-04-12 18:24 UTC, jayrevolinskyjr commented
Approved, looks like the re-base worked well.

2023-04-13 16:00 UTC, Jooms requested changes

2023-04-13 16:52 UTC, merged