Resolved linter semicolon issues. Fixes #48
ChicoState/PantryNode pull request #53
Opened 2023-03-09 06:48 UTC by parthpandey1

Changed rule in .eslintrc.cjs  for extra semicolons to show error instead of warning. Resolved extra semicolon issues.

2023-03-09 07:08 UTC, Jooms approved these changes
Approved with 1 comment to fix.

2023-03-09 07:08 UTC, Jooms commented on .eslintrc.cjs
> +        "@typescript-eslint/no-extra-semi": "error",
Just remove the entire line. `warn` was an override. Setting it to `error` is letting it go back to the default.

2023-03-09 17:22 UTC, jayrevolinskyjr requested changes
I agree with @Jooms , removing the no-extra-semi line will resolve this

2023-03-10 02:02 UTC, jayrevolinskyjr submitted a review, later dismissed
LGTM

2023-03-12 19:03 UTC, decoles commented
Looking good!

2023-03-12 19:04 UTC, decoles approved these changes

2023-03-28 06:53 UTC, parthpandey1 commented
rerun all

2023-03-28 06:53 UTC, parthpandey1 commented
retest all

2023-03-29 00:05 UTC, hardikpatil approved these changes

2023-03-29 04:51 UTC, jayrevolinskyjr approved these changes

2023-03-29 04:57 UTC, merged